POST https://api.clearlydefined.io/notices
{
  "coordinates": [
    "maven/mavencentral/aopalliance/aopalliance/1.0",
    "maven/mavencentral/org.slf4j/slf4j-api/1.7.36",
    "maven/mavencentral/org.springframework/spring-aop/5.3.19",
    "maven/mavencentral/org.springframework/spring-beans/5.3.19",
    "maven/mavencentral/org.springframework/spring-context/5.3.19",
    "maven/mavencentral/org.springframework/spring-core/5.3.19",
    "maven/mavencentral/SpEL) (org.springframework/spring-expression/5.3.19",
    "maven/mavencentral/org.springframework/spring-jcl/5.3.19",
    "maven/mavencentral/org.springframework.security/spring-security-config/4.2.20.RELEASE",
    "maven/mavencentral/org.springframework.security/spring-security-core/4.2.20.RELEASE",
    "maven/mavencentral/com.fasterxml.jackson.core/jackson-annotations/2.12.5",
    "maven/mavencentral/com.fasterxml.jackson.core/jackson-core/2.12.5",
    "maven/mavencentral/com.fasterxml.jackson.core/jackson-databind/2.12.5",
    "maven/mavencentral/com.github.andrewoma.dexx/collection/0.6",
    "maven/mavencentral/com.github.jsonld-java/jsonld-java/0.9.0",
    "maven/mavencentral/com.google.code.findbugs/jsr305/3.0.1",
    "maven/mavencentral/com.google.code.javaparser/javaparser/1.0.11",
    "maven/mavencentral/commons-beanutils/commons-beanutils/1.9.2",
    "maven/mavencentral/commons-cli/commons-cli/1.3",
    "maven/mavencentral/commons-collections/commons-collections/3.2.2",
    "maven/mavencentral/commons-io/commons-io/2.6",
    "maven/mavencentral/io.atlassian.fugue/fugue/4.4.0",
    "maven/mavencentral/org.apache.commons/commons-csv/1.3",
    "maven/mavencentral/org.apache.commons/commons-lang3/3.5",
    "maven/mavencentral/org.apache.httpcomponents/httpclient/4.5.3",
    "maven/mavencentral/org.apache.httpcomponents/httpclient-cache/4.5.2",
    "maven/mavencentral/org.apache.httpcomponents/httpcore/4.4.6",
    "maven/mavencentral/SPARQL 1.1 Query Engine) (org.apache.jena/jena-arq/3.3.0",
    "maven/mavencentral/org.apache.jena/jena-base/3.3.0",
    "maven/mavencentral/org.apache.jena/jena-core/3.3.0",
    "maven/mavencentral/org.apache.jena/jena-iri/3.3.0",
    "maven/mavencentral/org.apache.jena/jena-shaded-guava/3.3.0",
    "maven/mavencentral/Native Triple Store) (org.apache.jena/jena-tdb/3.3.0",
    "maven/mavencentral/org.apache.thrift/libthrift/0.9.3",
    "maven/mavencentral/org.jvnet.jaxb2_commons/jaxb2-basics/0.11.1",
    "maven/mavencentral/org.jvnet.jaxb2_commons/jaxb2-basics-runtime/0.11.1",
    "maven/mavencentral/org.jvnet.jaxb2_commons/jaxb2-basics-tools/0.11.1",
    "maven/mavencentral/org.slf4j/jcl-over-slf4j/1.7.36",
    "maven/mavencentral/xerces/xercesImpl/2.11.0",
    "maven/mavencentral/The SAX License) (The W3C License) XML Commons External Components XML APIs (xml-apis/xml-apis/1.4.01",
    "maven/mavencentral/com.google.guava/guava/20.0",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-domain/4.1.0-SNAPSHOT",
    "maven/mavencentral/org.springframework/spring-context-support/5.3.19",
    "maven/mavencentral/GNU Lesser General Public License) Logback Classic Module (ch.qos.logback/logback-classic/1.2.11",
    "maven/mavencentral/GNU Lesser General Public License) Logback Core Module (ch.qos.logback/logback-core/1.2.11",
    "maven/mavencentral/com.auth0/java-jwt/3.2.0",
    "maven/mavencentral/commons-codec/commons-codec/1.10",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-security/4.1.0-SNAPSHOT",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-test-support/4.1.0-SNAPSHOT",
    "maven/mavencentral/javax.servlet/javax.servlet-api/3.1.0",
    "maven/mavencentral/junit/junit/4.12",
    "maven/mavencentral/without dependencies) (net.bytebuddy/byte-buddy/1.6.11",
    "maven/mavencentral/net.bytebuddy/byte-buddy-agent/1.6.11",
    "maven/mavencentral/org.bouncycastle/bcprov-jdk15on/1.55",
    "maven/mavencentral/org.hamcrest/hamcrest-core/1.3",
    "maven/mavencentral/org.hamcrest/hamcrest-library/1.3",
    "maven/mavencentral/org.mockito/mockito-core/2.7.22",
    "maven/mavencentral/org.objenesis/objenesis/2.5",
    "maven/mavencentral/org.springframework/spring-test/5.3.19",
    "maven/mavencentral/org.springframework/spring-web/5.3.19",
    "maven/mavencentral/org.springframework.security/spring-security-web/4.2.20.RELEASE",
    "maven/mavencentral/org.webjars/MathJax/2.7.0",
    "maven/mavencentral/com.sun.xml.bind/jaxb-core/2.2.11",
    "maven/mavencentral/com.sun.xml.bind/jaxb-impl/2.2.11",
    "maven/mavencentral/javax.inject/javax.inject/1",
    "maven/mavencentral/org.apache.chemistry.opencmis/chemistry-opencmis-client-api/1.1.0",
    "maven/mavencentral/org.apache.chemistry.opencmis/chemistry-opencmis-client-bindings/1.1.0",
    "maven/mavencentral/org.apache.chemistry.opencmis/chemistry-opencmis-client-impl/1.1.0",
    "maven/mavencentral/org.apache.chemistry.opencmis/chemistry-opencmis-commons-api/1.1.0",
    "maven/mavencentral/org.apache.chemistry.opencmis/chemistry-opencmis-commons-impl/1.1.0",
    "maven/mavencentral/org.apache.cxf/cxf-core/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-bindings-soap/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-bindings-xml/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-databinding-jaxb/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-frontend-jaxws/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-frontend-simple/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-transports-http/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-ws-addr/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-ws-policy/3.0.12",
    "maven/mavencentral/org.apache.cxf/cxf-rt-wsdl/3.0.12",
    "maven/mavencentral/org.apache.neethi/neethi/3.0.3",
    "maven/mavencentral/org.apache.ws.xmlschema/xmlschema-core/2.2.1",
    "maven/mavencentral/org.codehaus.woodstox/stax2-api/3.1.4",
    "maven/mavencentral/org.codehaus.woodstox/woodstox-core-asl/4.4.1",
    "maven/mavencentral/LGPL 2.1) (MPL 1.1) Javassist (org.javassist/javassist/3.21.0-GA",
    "maven/mavencentral/org.powermock/powermock-api-mockito-common/1.7.4",
    "maven/mavencentral/org.powermock/powermock-api-mockito2/1.7.4",
    "maven/mavencentral/org.powermock/powermock-api-support/1.7.4",
    "maven/mavencentral/org.powermock/powermock-core/1.7.4",
    "maven/mavencentral/org.powermock/powermock-module-junit4/1.7.4",
    "maven/mavencentral/org.powermock/powermock-module-junit4-common/1.7.4",
    "maven/mavencentral/org.powermock/powermock-reflect/1.7.4",
    "maven/mavencentral/wsdl4j/wsdl4j/1.6.3",
    "maven/mavencentral/xml-resolver/xml-resolver/1.2",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-config/4.1.0-SNAPSHOT",
    "maven/mavencentral/com.narupley/not-going-to-be-commons-ssl/0.3.20",
    "maven/mavencentral/commons-httpclient/commons-httpclient/3.1",
    "maven/mavencentral/commons-lang/commons-lang/2.6",
    "maven/mavencentral/joda-time/joda-time/2.2",
    "maven/mavencentral/org.apache.santuario/xmlsec/1.5.8",
    "maven/mavencentral/org.apache.velocity/velocity-engine-core/2.0",
    "maven/mavencentral/org.bouncycastle/bcpkix-jdk15on/1.55",
    "maven/mavencentral/org.bouncycastle/bcprov-ext-jdk15on/1.55",
    "maven/mavencentral/org.opensaml/opensaml/2.6.6",
    "maven/mavencentral/org.opensaml/openws/1.5.6",
    "maven/mavencentral/org.opensaml/xmltooling/1.4.6",
    "maven/mavencentral/Creative Commons 3.0 BY-SA) ESAPI (org.owasp.esapi/esapi/2.1.0.1",
    "maven/mavencentral/org.springframework.security.extensions/spring-security-saml2-core/1.0.9.RELEASE",
    "maven/mavencentral/xalan/serializer/2.7.2",
    "maven/mavencentral/xalan/xalan/2.7.2",
    "maven/mavencentral/com.googlecode.java-diff-utils/diffutils/1.3.0",
    "maven/mavencentral/com.ibm.icu/icu4j/60.2",
    "maven/mavencentral/com.thoughtworks.xstream/xstream/1.4.9",
    "maven/mavencentral/cool.graph/cuid-java/0.1.1",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-i18n/4.1.0-SNAPSHOT",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-integration/4.1.0-SNAPSHOT",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-repository/4.1.0-SNAPSHOT",
    "maven/mavencentral/io.micrometer/micrometer-core/1.6.3",
    "maven/mavencentral/io.netty/netty-buffer/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-codec/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-codec-http/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-codec-socks/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-common/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-handler/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-handler-proxy/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-resolver/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-tcnative-classes/2.0.46.Final",
    "maven/mavencentral/io.netty/netty-transport/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-transport-classes-epoll/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-transport-classes-kqueue/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-transport-native-epoll/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-transport-native-kqueue/4.1.73.Final",
    "maven/mavencentral/io.netty/netty-transport-native-unix-common/4.1.73.Final",
    "maven/mavencentral/GNU General Public License, version 2 with the GNU Classpath Exception) Jakarta Messaging API (jakarta.jms/jakarta.jms-api/2.0.3",
    "maven/mavencentral/GNU General Public License, version 2 with the GNU Classpath Exception) Jakarta JSON Processing API (jakarta.json/jakarta.json-api/1.1.6",
    "maven/mavencentral/GPL2 w/ CPE) javax.transaction API (jakarta.transaction/jakarta.transaction-api/1.3.3",
    "maven/mavencentral/javax.websocket/javax.websocket-api/1.1",
    "maven/mavencentral/jaxen/jaxen/1.2.0",
    "maven/mavencentral/net.sf.ehcache/ehcache/2.10.9.2",
    "maven/mavencentral/net.sf.saxon/Saxon-HE/9.8.0-3",
    "maven/mavencentral/org.apache.activemq/artemis-commons/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-core-client/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-jdbc-store/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-jms-client/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-jms-server/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-journal/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-quorum-api/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-selector/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-server/2.19.1",
    "maven/mavencentral/org.apache.activemq/artemis-service-extensions/2.19.1",
    "maven/mavencentral/org.apache.commons/commons-configuration2/2.7",
    "maven/mavencentral/org.apache.commons/commons-dbcp2/2.7.0",
    "maven/mavencentral/org.apache.commons/commons-pool2/2.7.0",
    "maven/mavencentral/org.apache.commons/commons-text/1.4",
    "maven/mavencentral/org.apache.johnzon/johnzon-core/0.9.5",
    "maven/mavencentral/org.freemarker/freemarker/2.3.27-incubating",
    "maven/mavencentral/Public Domain, per Creative Commons CC0) HdrHistogram (org.hdrhistogram/HdrHistogram/2.1.12",
    "maven/mavencentral/org.jboss.logging/jboss-logging/3.3.0.Final",
    "maven/mavencentral/org.jctools/jctools-core/2.1.2",
    "maven/mavencentral/org.jgroups/jgroups/3.6.13.Final",
    "maven/mavencentral/org.jsoup/jsoup/1.14.3",
    "maven/mavencentral/org.latencyutils/LatencyUtils/2.0.3",
    "maven/mavencentral/org.springframework/spring-jms/5.3.19",
    "maven/mavencentral/org.springframework/spring-messaging/5.3.19",
    "maven/mavencentral/org.springframework/spring-tx/5.3.19",
    "maven/mavencentral/org.springframework/spring-webmvc/5.3.19",
    "maven/mavencentral/org.springframework/spring-websocket/5.3.19",
    "maven/mavencentral/com.google.gwt/gwt-elemental/2.8.2",
    "maven/mavencentral/com.google.gwt/gwt-user/2.8.2",
    "maven/mavencentral/com.google.jsinterop/jsinterop-annotations/1.0.2",
    "maven/mavencentral/com.vaadin/vaadin-client/8.14.3",
    "maven/mavencentral/com.vaadin/vaadin-compatibility-client/8.14.3",
    "maven/mavencentral/com.vaadin/vaadin-compatibility-server/8.14.3",
    "maven/mavencentral/com.vaadin/vaadin-compatibility-shared/8.14.3",
    "maven/mavencentral/com.vaadin/vaadin-sass-compiler/0.9.13",
    "maven/mavencentral/com.vaadin/vaadin-server/8.14.3",
    "maven/mavencentral/com.vaadin/vaadin-shared/8.14.3",
    "maven/mavencentral/com.vaadin/vaadin-spring/3.2.1",
    "maven/mavencentral/com.vaadin/vaadin-themes/8.14.3",
    "maven/mavencentral/com.vaadin.addon/vaadin-onoffswitch/1.1.0",
    "maven/mavencentral/com.vaadin.external/gentyref/1.2.0.vaadin1",
    "maven/mavencentral/com.vaadin.external.flute/flute/1.3.0.gg2",
    "maven/mavencentral/com.vaadin.external.gwt/gwt-elemental/2.8.2.vaadin2",
    "maven/mavencentral/com.yahoo.platform.yui/yuicompressor/2.4.8",
    "maven/mavencentral/de.datenhahn.vaadin/componentrenderer/2.0.0",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-js/4.1.0-SNAPSHOT",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-services/4.1.0-SNAPSHOT",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-use-cases/4.1.0-SNAPSHOT",
    "maven/mavencentral/javax.validation/validation-api/1.1.0.Final",
    "maven/mavencentral/org.slf4j/jul-to-slf4j/1.7.36",
    "maven/mavencentral/org.vaadin/simplefiledownloader/2.1",
    "maven/mavencentral/org.vaadin.addon/confirmdialog/3.2.0",
    "maven/mavencentral/org.vaadin.addons/autocomplete/0.2.4",
    "maven/mavencentral/org.vaadin.addons/vaadin-sliderpanel/2.2.1",
    "maven/mavencentral/org.vaadin.anna/dndscroll/2.0.2",
    "maven/mavencentral/org.vaadin.olli/v8-client-storage/0.1",
    "maven/mavencentral/org.vaadin.teemusa/gridextensionpack/2.0.0",
    "maven/mavencentral/org.w3c.css/sac/1.3",
    "maven/mavencentral/rhino/js/1.7R2",
    "maven/mavencentral/com.squareup.okhttp3/okhttp/3.7.0",
    "maven/mavencentral/com.squareup.okio/okio/1.12.0",
    "maven/mavencentral/commons-fileupload/commons-fileupload/1.3.3",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-security-preauth/4.1.0-SNAPSHOT",
    "maven/mavencentral/eu.europa.ec.leos.pilot/leos-ui/4.1.0-SNAPSHOT",
    "maven/mavencentral/org.slf4j/log4j-over-slf4j/1.7.36"
  ],
  "renderer": "json",
  "options": {}
}